name: Keycloak GitHub bot

# This GitHub bot listens on comments in the repository and reruns failed GitHub actions:
# When adding a new comment '/rerun' as is on a pull request that is open, the bot will re-run any failed jobs in a workflow run.
# The user commenting needs to be either a collaborator, an owner, a member of the organization or a contributor.

# See https://github.com/keycloak/keycloak-gh-actionbot for more information

on:
  issue_comment:
    types:
      - created

permissions:
  actions: write
  pull-requests: write

jobs:
  act:
    runs-on: ubuntu-latest
    steps:
      # to avoid a tag being changed afterwards, use the commit hash of the action
      - uses: keycloak/keycloak-gh-actionbot@33d8759517f1bfbb70d52fa1f6d58ef2e824301b # v0.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
